name: Testing, Formatting & Deployment
run-name: ${{ github.actor }} is having a blast
on: [push]
jobs:
  Test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: RUN TESTS
      - run: npm test
