on:
  push:
    branches:
      - dev

name: Testing

run-name: ${{ github.actor }} is doing their best

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: npm install
        run: npm install

      - name: Run tests with Jest
        run: npm test
